### ISSUE TITLE
Getting Started tutorial destroys card data in profile

### ISSUE THREAD

**Issue by lechten** [solid/solidproject.org#546]
**Search terms you've used**
getting started, tutorial

**Describe the bug**
I followed the [Getting Started tutorial](https://solidproject.org/developers/tutorials/getting-started). Writing the name destroys the card data. Sample profile, where I wrote "Testname": https://tutorial-bug.solidcommunity.net/profile/card

```
;
    <http://www.w3.org/2006/vcard/ns#fn> "Testname".
```

Note that the name was not changed, but the new name replaced the entire card data.

**To Reproduce**
1. Build the application
2. Login
3. Write a name
4. Try to read the name. See this: "Error: Expected entity but got ; on line 1."

**Expected behavior**
The name should be changed, not replace the entire card data.

**Screenshots**
![2021-03-25 12-17-51](https://user-images.githubusercontent.com/16863240/112464945-696e1480-8d64-11eb-89af-9e77781465ef.png)

**Desktop:**
 - OS: PureOS
 - Browser: Firefox
 - Version: 86.0.1

**Comment by NSeydoux** [comment]
Hi @lechten , and thanks for reporting this ! The issue comes from a bug in https://github.com/inrupt/solid-client-js, and we identified what's causing it. We'll implement a fix as soon as possible, and update this issue when the fix is released. 

I'm sorry that your profile got overwritten. The bug was introduced as a side effect to a fix of another bug recently, and it's quite bad that it impacts this tutorial, so thank you for spotting it and preventing other users to get their profiles erased.
