### ISSUE TITLE
Pin 'Calls for Feedback' as read-only forum topic

### ISSUE THREAD

**Issue by woutermont** [solid/solidproject.org#797]
In the light of the commotion aroung @jeff-zucker's [comment](https://github.com/solid/process/pull/323#issuecomment-1623993979) on solid/process/pull/323, I took the liberty of creating a '[Calls for Feedback](https://forum.solidproject.org/t/calls-for-feedback/6745)' topic on the forum, intended to be a central place of reference to new major work items, in order to reach a wider part of the community.

My question here is whether the admins could pin this topic to the top and, if possible, make it read-only except for editors and chairs.

**Comment by jeff-zucker** [comment]
While it strikes me as a generally a good idea, I would much prefer that this be raised as an issue before you taking unilateral action.  There is a Team and moderators who facilitate the forum.  This kind of unilateral action is why I "raised a commotion" in the CG.  Random piecemeal approaches to community building are bound to fail.  Previously  new topic areas in the forum were discussed among the Team and the Forum moderators for among other reasons developing policies about if and how special moderation is needed (as we did for the Applications section of the forum).

**Comment by VirginiaBalseiro** [comment]
The topic is labeled as being in the Specification category:

![image](https://github.com/solid/solidproject.org/assets/28412960/05097dfb-655b-4e25-9c1c-3cb19325bd41)

**Comment by woutermont** [comment]
Perfect! Thank for the quick follow-up, @jeff-zucker.

If it is indeed not possible to let a specific group of people post to it, could you add to my topic opener which people we can contact to add calls?

An alternative solution would be that we leave it unlocked, and should someone reply in the topic anyways politely remove/hide their post, refering to the topic's purpose.

**Comment by jeff-zucker** [comment]
The changing list of moderators and admins of the forum (who would have the ability to edit locked topics) is always available at https://forum.solidproject.org/about.  If you prefer to leave the discussion open and edit replies, just let me know and I'll remove the lock.

**Comment by jeff-zucker** [comment]
I pinned the Call inside the Specifications topic.  Is that sufficient to meet your needs?

**Comment by woutermont** [comment]
Well, I think this a perfect example of the distinct functions of communication between the CG and the Team: the CG can only provide the data to be communicated (e.g. the charter PR); whether a forum topic for this communication reaches a sufficiently wide audience in de Specification subcategory is entirely up to the Team.

I do think leaving it unlocked would be easier though.

**Comment by jeff-zucker** [comment]
Sure, if you want it unlocked, I'll unlock it.

Good point on the communication between the Team and the CG.  Reaching a wider audience is not just a matter of where things are placed in the forum but whom they are addressed to.  Yours is addressed to people who understand terms like "CG" and "WG" which leaves most forum members scratching their heads.  If we have a recognized function for community engagement (whether it live in the Project or the CG), it could serve as a resource to help use inclusive messaging.  People who are engaged in things tend to make assumptions about what is understood, acronyms being only the tip of the iceberg.  My "commotion" about having the community engagement function within the CG was my way of attempting to get more coordination between the efforts so that things like your Call were more accessible to others than those already involved.  Your reaching out to the forum was a great first step, but there is more to be done.

**Comment by jeff-zucker** [comment]
See, for example the discussion following this [comment on the forum](https://forum.solidproject.org/t/why-backend-for-frontend-for-solid-is-categorically-wrong/6673/14?u=jeffz_.  Reorienting the discussion to be more inclusive in language literally brought someone into the discussion who had previously not been able to penetrate it.  We need this kind of attention to those not already in the know at all levels of Solid.

**Comment by woutermont** [comment]
I understand the need for accessibility, and I agree we can in general pay more attention to it. Since that is not a spec-specific issue, however, it is i.m.o. up to the team to raise more awareness for it. (In this case: thanks for doing so; I'll edit my post.)

**Comment by jeff-zucker** [comment]
The Team didn't have time to get to this agenda item so I preemptively pinned it globally which means that all users will see it at the top of the list of posts.  It will remain pinned globally until August 1.  BTW, great job on making the call more welcoming/inclusive.

**Comment by jeff-zucker** [comment]
@woutermont - it looks like I can pin a topic but not a post within the topic so maybe you want to temporarily edit the topic title to be Call for feedback on the Community Group Charter and the text to be aimed at users of the forum rather than the editors.  Just a suggestion, it looks a bit funny to me pinned as-is.

**Comment by jeff-zucker** [comment]
I especially do not like "PLEASE DO NOT REACT" in caps as the first thing a reader sees when entering the entire forum.

**Comment by woutermont** [comment]
Oh, right, I'll see what I can do about the caps.

Re the title: the intention was to have a single pinned topic where people can immediately see if there are any new calls for feedback, and I believe the title makes that clear. Did you interpret it differently?

**Comment by jeff-zucker** [comment]
I mean specifically the title as it appears on the globally pinned topic.  The reason for globally pinning it is so that people can see and respond to the calls.  You're not asking readers to respond to a generic call, you're asking them to respond about the charter.  In the future another call would supersede it and you'd change the title on the globally pinned description so it always describes the thing you want feedback on.  We can also pin your more general description of the topic inside the topic.  That  way the description that appears in the table of contents is always specific to what you are asking but as soon as someone clicks on it, they see your general message about how to respond, etc.

**Comment by woutermont** [comment]
Hm, I see what you mean, but I'm still unsure whether that's a good idea. We always want people to give feedback on any of the current topics. If in one week, editors add three new calls for feedback, for example, what should the title be? People will always see immediately when something new is posted in the thread (because of the unread counter), and if they want to check out what it is, they can simply click on the topic. Would that not suffice?

Also, we're past the editing time limit for the opening post. If you can remove that limit, or edit the post as moderator, I would suggest inserting a thematic break before the caps, so the pinned topic only shows the first line as intro.

**Comment by jeff-zucker** [comment]
You can worry about all that in the future.  We may decide to have some different kind of pinned disambiguation page that points users to the key feedback areas of several kinds.  For now you want feedback on the charter and my opinion is that you should ask for it in a way that people can understand what they are being invited to do.  But up to you.   If you want to edit and can't edit directly, just send to me (on the forum itself please - @jeffz).
