### ISSUE TITLE
CSS misaligned on main page

### ISSUE THREAD

**Issue by michielbdejong** [solid/solidproject.org#866]
<img width="1616" alt="Screenshot 2024-04-04 at 08 49 02" src="https://github.com/solid/solidproject.org/assets/408412/271a8724-fda1-4e83-aa15-6d4c9b0c377b">

**Comment by csarven** [comment]
I presume this has to do with the new item being added to the homepage ( introduced in https://github.com/solid/solidproject.org/pull/863 ) and to handle arbitrary number of items. I've pushed a fix into https://github.com/solid/solidproject.org/commit/d565ea3f639d812ff62d8583d1212128509433b6 . That should work. Let me know / close issue at will.

I've made the best guess here because we don't have IA / UX documentations or a style guide.

**Comment by michielbdejong** [comment]
Much better, thanks a lot! That fixes the missing grid lines:
<img width="1608" alt="Screenshot 2024-04-09 at 14 42 33" src="https://github.com/solid/solidproject.org/assets/408412/6e79b5c9-7b48-4fdd-aa25-1b66d6ca173b">

But I think there still is a text indentation problem. I would expect texts to be left-aligned, so that "Develop an app with Solid" to start at the same x position as "Read about Solid". Instead it seems each text is centered?

**Comment by michielbdejong** [comment]
That's better! And I learned something about CSS grids in the process :) Thanks!

<img width="1608" alt="Screenshot 2024-04-09 at 15 07 00" src="https://github.com/solid/solidproject.org/assets/408412/7fa0e96b-254c-46a6-abb7-615ee4551a01">
